### ISSUE TITLE
NaN in density grid

### ISSUE THREAD

**Issue by fishfishson** [kwea123/ngp_pl#38]
Hi author, thx for your amazing repo!
When I train on an indoor scene I find nan values appear in the density grid which leads to errors like:
> in sample_uniform_and_occupied_cells                                    
> cells += [(torch.cat([indices1, indices2]), torch.cat([coords1, coords2]))]
> RuntimeError: CUDA error: invalid configuration argument

Could you pls tell me how to fix this like setting an upper bound value for the density grid during training?

**Comment by kwea123** [comment]
Hi, I have never encountered this kind of error in my experiment (maybe nan occurs but no error appeared)
If you want to change density grid, you can do it here:
https://github.com/kwea123/ngp_pl/blob/9b5427e7089b2dab4b2247d52beb71b324f08339/models/networks.py#L260-L263

Let me know if it helps!

**Comment by hdzmtsssw** [comment]
Hi, I also encountered this in my experiment. I found the reason is that the learning rate is too large. So I decrease 'lr' in my settings, it works.

**Comment by summersnowfish** [comment]
Hello, I also encountered a similar problem to you. I later reconfigured the environment and solved it. I think it may be that the versions of torch-scatter and TorchMetrics are not installed correctly. Regarding torch-scatter, you need to find the version matching your cuda and pytorch at https://pytorch-geometric.com/whl/. I solved the error after doing this. Hope this helps.
