### ISSUE TITLE
colmap data  render error

### ISSUE THREAD

**Issue by Xiaxia1997** [kwea123/ngp_pl#61]
I tried to use [nerf_llff_data](https://drive.google.com/file/d/16VnMcF1KJYxN9QId6TClMsZRahHNMW5g/view?usp=sharing) with colmap.py. But the rendering part crashed after training. 
Here is my command:`python train.py --root_dir ./ngp_pl-master/data/nerf_llff_data/fern --exp_name test_example --batch_size 16384 --dataset_name colmap --downsample 4.0 --num_epochs 30`
And the error message is:
Epoch 0: 100%|█████████████████████████████████████████████████████████████████████▊| 1000/1003 [00:37<00:00, 26.33it/s, loss=0.00569, train/s_per_ray=126.0,raceback (most recent call last):                                                                                                                        | 0/
  File "train.py", line 337, in <module>
    trainer.fit(system, ckpt_path=hparams.ckpt_path)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 266, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 205, in run
    self.on_advance_end()
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 255, in on_advance_end
    self._run_validation()
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 311, in _run_validation
    self.val_loop.run()
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 128, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 226, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1765, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 344, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "train.py", line 257, in validation_step
    results = self(batch, split='test')
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "train.py", line 147, in forward
    return render(self.model, rays_o, rays_d, **kwargs)
  File "/home/x00586938/ngp_pl-master/models/rendering.py", line 35, in render
    results = render_func(model, rays_o, rays_d, hits_t, **kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/x00586938/ngp_pl-master/models/rendering.py", line 83, in __render_rays_test
    vren.raymarching_test(rays_o, rays_d, hits_t[:, 0], alive_indices,
RuntimeError: CUDA out of memory. Tried to allocate 2.18 GiB (GPU 0; 23.70 GiB total capacity; 16.93 GiB already allocated; 2.00 GiB free; 17.71 GiB reservedch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA
Epoch 0: 100%|█████████████████████████████████████████████████████████████████████▊| 1000/1003 [00:56<00:00, 17.57it/s, loss=0.00569, train/s_per_ray=126.0

**Comment by Xiaxia1997** [comment]
And [HDR-NeRF data](https://drive.google.com/drive/folders/1OTDLLH8ydKX1DcaNpbQ46LlP0dKx6E-I) works well.

**Comment by kwea123** [comment]
As the error says, this is `RuntimeError: CUDA out of memory.`

First please check how much GPU memory you have, `--batch_size 16384` requires at least 12GB in my opinion, if your gpu has smaller memory, please lower this number. Next `--downsample` should be **<1**, if you want to train on 1/4 scale, set this number to `0.25` instead of `4.0`. Finally, `nerf_llff` data requires a `scale` that is larger, I don't have the number in mind (maybe I should add this benchmark too), but I remember that the `scale` for `fern` is around 4.0

**Comment by Xiaxia1997** [comment]
Thanks a lot, I've changed the two paremeters and it works well now.
