### ISSUE TITLE
CUDA error: invalid configuration argument

### ISSUE THREAD

**Issue by jianglh-WHU** [kwea123/ngp_pl#95]
hi~I use my own synethtic data to train ngp_pl,but unfortunately, I suddenly encountered an error here, can you help me solve it?
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/71580859/198948735-debf65fd-c152-4ee9-9e0e-eccab3040910.png">

**Comment by kwea123** [comment]
it's because all the cells in the density grid become empty, usually it's because you set a too high alpha threshold, too high distortion loss weight, or your rays doesn't intersect with the bounding box at all, can you verify if anything meets? you can use the notebook to visualize the box and the rays (you need some coding)

**Comment by summersnowfish** [comment]
Hello, I also encountered a similar problem to you. I later reconfigured the environment and solved it. I think it may be that the versions of torch-scatter and TorchMetrics are not installed correctly. Regarding torch-scatter, you need to find the version matching your cuda and pytorch at https://pytorch-geometric.com/whl/. I solved the error after doing this. Hope this helps.

**Comment by KexuanShi** [comment]
I also find this question. However, this mistake happens when I replace the tcNN network with the linear layer of pytorch. I think that this error is caused by the NAN of loss. I don't know how to solve it. Can you give me some help？
